services:
    fluid:
        class: TYPO3Fluid\Fluid\View\TemplateView

    fluid.renderingContext:
        class: Mia3\FluidBundle\Fluid\Core\Rendering\RenderingContext
        arguments:
          - "@fluid"

    templating.engine.fluid:
        class: Mia3\FluidBundle\FluidEngine
        arguments:
            - "@fluid"
            - "@file_locator"
            - "@service_container"